version: '2.2'

services:
  redis:
    image: redis
    restart: "no"
    entrypoint: redis-server --appendonly yes
    volumes:
      - ./tmpdata/redis:/data

  goplasma:
    build:
      context: ./
      dockerfile: Dockerfile_standalone
    image: result/latest
    environment:
      - REDIS_HOST=redis
      - SERVICE_PORTS=3001
    ulimits:
      nproc: 65535
      nofile:
        soft: 30000
        hard: 30000
